version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    # command: sh -c "fastapi dev main.py"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    env_file:
      - ./backend/.env
    networks:
      - vintednetwork

  # frontend:
  #   build: ./frontend
  #   container_name: frontend
  #   ports:
  #     - "3000:80"
  #   networks:
  #     - vintednetwork

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: myhashedpassword
      POSTGRES_DB: vinteddatabase
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - vintednetwork

networks:
  vintednetwork:
    driver: bridge

volumes:
  pgdata:
